name: Generate Snake Animation
on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@master
        with:
          github_user_name: Dineshkumar245
          svg_out_path: dist/github-contribution-grid-snake.svg
      - run: git add dist/github-contribution-grid-snake.svg
      - run: git commit -m "Update Snake animation"
      - run: git push
